esphome:
  name: esptest
  friendly_name: esptest

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esptest Fallback Hotspot"
    password: ""

captive_portal:
    
# default I2C Bus config (ESP32-S2-Mini)
i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    scan: true

sensor:
# BMP280 for I2C testing
  - platform: bmp280_i2c
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Air Pressure"
    update_interval: 60s
    i2c_id: bus_a
    address: 0x76
# ADC (ESP-Mini-Base, using 3.3V measurement)
  - platform: adc
    name: "Battery voltage"
    pin: GPIO3
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 2.5dB
    samples: 5
    filters:
      - multiply: 4.348  # muliplier given by ESP-Mini-Base voltage divider
# ESP internal temperature probe
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"

# Onboard-LED (ESP32-S2-Mini)
# and MOSFET outputs (ESP-Mini-Base)
output:
  - platform: ledc
    pin: GPIO15
    id: led_pin
    frequency: "4882Hz"
  - platform: ledc
    pin: GPIO1
    id: Fet_Q1
    frequency: "4882Hz"
  - platform: ledc
    pin: GPIO2
    id: Fet_Q2
    frequency: "4882Hz"
  - platform: ledc
    pin: GPIO4
    id: Fet_Q3
    frequency: "4882Hz"
light:
  - platform: monochromatic
    output: led_pin
    id: led_light
    name: "ESP LED Dimmable"
    effects:
      - pulse:
          name: "Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
# Example MOSFET usage for RGB Strip
  - platform: rgb
    name: "RGB LED Strip"
    red: Fet_Q1
    green: Fet_Q2
    blue: Fet_Q3

# Pushbutton (ESP-Mini-Base)
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true # Button is "active low"
      mode:
        input: true
        pullup: false # has external PU
    name: "Button"
    interrupt_type: ANY #FALLING/RISING not working with ESP32-S2-Mini!
    filters:
    - delayed_on: 50ms
    - delayed_off: 50ms
    on_press:
      then:
        - light.toggle: led_light

# SSR (ESP-Mini-Base)
switch:
  - platform: gpio
    pin: GPIO13
    name: "SSR"
    id: ssr
